services:
  kafka-producer-1:
    image: us-stock-rt-kafka:v1.0
    container_name: kafka-producer-1
    command: ["python", "-m", "src.kafka_src.producer.producer_1"]
    restart: on-failure
    env_file:
      - .env
    networks:
      - realtime-network
  
  kafka-producer-2:
    image: us-stock-rt-kafka:v1.0
    container_name: kafka-producer-2
    command: ["python", "-m", "src.kafka_src.producer.producer_2"]
    restart: on-failure
    env_file:
      - .env
    networks:
      - realtime-network

  kafka-consumer-alert:
    image: us-stock-rt-kafka:v1.0
    container_name: kafka-consumer-alert
    command: ["python", "-m", "src.kafka_src.consumer.consumer_alert"]
    restart: on-failure
    env_file:
      - .env
    networks:
      - realtime-network

  kafka-consumer-minio:
    image: us-stock-rt-kafka:v1.0
    container_name: kafka-consumer-minio
    command: ["python", "-m", "src.kafka_src.consumer.consumer_minio"]
    restart: on-failure
    env_file:
      - .env
    networks:
      - realtime-network

networks:
  realtime-network:        # compose 內部引用的別名
    external: true
    name: realtime-workspace_default # 指定實際的網路名稱
